version: '3'

services:
  netarise:
    build: .
    container_name: netarise
    restart: on-failure
    command: ["node", "server.js"]
    network_mode: "host"  # Utilise directement les interfaces réseau de l'hôte
    volumes:
      - ./devices.csv:/app/devices.csv
      - ./logs/netarise.log:/app/logs/netarise.log
    environment:
      - INTERFACE=eth0
      - PORT=8085  # Comme nous utilisons le réseau host, nous définissons le port ici

# Pas besoin de définir des réseaux quand on utilise network_mode: "host"